#!/usr/bin/env node
/*
 * tokens.js — mechanical design tokens from the measured workspace.
 *
 *   node tokens.js <workspace> [--out build/tokens.css]
 *
 * Keeps the site's own :root custom properties verbatim (their names are the
 * best token names available), then adds measured, frequency-ranked tokens.
 * No interpretation: every value maps to an extracted value.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const B = require('./lib/browser');

const args = B.parseArgs(process.argv.slice(2), { out: { type: 'string' } });
const WS = path.resolve(args._[0] || '.');
const capture = B.readJson(path.join(WS, 'capture.json'));
const P = capture.meta.primary;
const tokens = B.readJson(path.join(WS, 'tokens-' + P + '.json'));
const motion = B.readJson(path.join(WS, 'motion.json'), { transitions: [] });
const out = path.resolve(args.out || path.join(WS, 'build', 'tokens.css'));
B.ensureDir(path.dirname(out));

function hex(rgb) { const m = /rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/.exec(rgb || ''); if (!m) return rgb; const a = m[4] !== undefined ? parseFloat(m[4]) : 1; const h = '#' + [m[1], m[2], m[3]].map(n => Number(n).toString(16).padStart(2, '0')).join(''); return a < 1 ? h + Math.round(a * 255).toString(16).padStart(2, '0') : h; }
function role(where) { const w = (where || []).join(' '); if (/^bg|\bbg /.test(w)) return 'bg'; if (/text /.test(w)) return 'text'; if (/border /.test(w)) return 'border'; return 'color'; }
function safeName(s) { return s.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase(); }

const L = ['/* Design tokens — generated by clone-website tokens.js from ' + capture.meta.url, ' * measured at ' + P + 'px on ' + capture.meta.extractedAt, ' * Regenerate rather than hand-edit; per-section values live in specs/. */', '', ':root {'];
const cp = tokens.customProps || {};
const cpKeys = Object.keys(cp);
if (cpKeys.length) { L.push('  /* ── the site\'s own custom properties (verbatim, ' + cpKeys.length + ') ── */'); cpKeys.forEach(k => L.push('  ' + k + ': ' + cp[k] + ';')); L.push(''); }
L.push('  /* ── typography (measured) ── */');
L.push('  --font-body: ' + tokens.body.fontFamily + ';');
const headingFont = (tokens.headings.h1 || tokens.headings.h2 || {}).fontFamily; if (headingFont && headingFont !== tokens.body.fontFamily) L.push('  --font-heading: ' + headingFont + ';');
const families = []; (tokens.fonts || []).forEach(f => { const fam = f.value.split(' / ')[0]; if (!families.includes(fam)) families.push(fam); });
families.slice(0, 4).forEach((f, i) => L.push('  --font-' + (i + 1) + ': ' + f + ';'));
const sizes = Array.from(new Set((tokens.typeScale || []).map(t => t.value.split(' / ')[0]))).map(s => parseFloat(s)).filter(n => n > 0).sort((a, b) => a - b);
sizes.forEach((s, i) => L.push('  --text-' + (i + 1) + ': ' + s + 'px;'));
const lh = Array.from(new Set((tokens.lineHeights || []).map(t => t.value))).slice(0, 8); lh.forEach((v, i) => L.push('  --leading-' + (i + 1) + ': ' + v + ';'));
const weights = Array.from(new Set((tokens.fonts || []).map(f => f.value.split(' / ')[1]))).sort(); weights.forEach(w => L.push('  --weight-' + w + ': ' + w + ';'));
const ls = (tokens.letterSpacing || []).filter(t => !t.value.startsWith('transform:') && t.value !== 'normal').slice(0, 6); ls.forEach((t, i) => L.push('  --tracking-' + (i + 1) + ': ' + t.value + ';'));
L.push('');
L.push('  /* ── colors (frequency-ranked; role from where the value paints) ── */');
const seenC = {}; (tokens.colors || []).forEach(c => { const r = role(c.where); const n = (seenC[r] = (seenC[r] || 0) + 1); L.push('  --color-' + r + '-' + n + ': ' + hex(c.value) + '; /* ' + c.count + '× e.g. ' + (c.where[0] || '') + ' */'); });
(tokens.gradients || []).slice(0, 6).forEach((g, i) => L.push('  --gradient-' + (i + 1) + ': ' + g.value + ';'));
L.push('');
L.push('  /* ── spacing scale (values used ≥3×, ascending) ── */');
const sp = (tokens.spacing || []).filter(s => s.count >= 3).map(s => parseFloat(s.value)).filter(n => n > 0); Array.from(new Set(sp)).sort((a, b) => a - b).forEach((v, i) => L.push('  --space-' + (i + 1) + ': ' + v + 'px;'));
L.push('');
L.push('  /* ── shape ── */');
(tokens.radii || []).slice(0, 8).forEach((r, i) => L.push('  --radius-' + (i + 1) + ': ' + r.value + ';'));
(tokens.shadows || []).slice(0, 8).forEach((s, i) => L.push('  --shadow-' + (i + 1) + ': ' + s.value + ';'));
(tokens.maxWidths || []).slice(0, 6).forEach((m, i) => L.push('  --container-' + (i + 1) + ': ' + m.value + ';'));
L.push('');
L.push('  /* ── motion ── */');
(motion.transitions || []).slice(0, 8).forEach((t, i) => L.push('  --transition-' + (i + 1) + ': ' + t.duration + ' ' + t.easing + '; /* ' + t.property + ' ' + t.count + '× */'));
L.push('');
L.push('  /* ── page ── */');
L.push('  --page-bg: ' + hex(tokens.body.background) + ';');
L.push('  --page-fg: ' + hex(tokens.body.color) + ';');
L.push('}');
if ((tokens.breakpoints || []).length) L.push('\n/* authored @media breakpoints seen in the stylesheets: ' + tokens.breakpoints.join(', ') + ' */');
if ((tokens.fontFaces || []).length) { L.push('\n/* @font-face declarations found on the original (' + tokens.fontFaces.length + '). Re-declare with local files from assets/fonts/. */'); tokens.fontFaces.slice(0, 20).forEach(f => L.push('/* ' + f.family + ' ' + f.weight + ' ' + f.style + ' — ' + f.src.slice(0, 160) + ' */')); }
if ((tokens.fontLinks || []).length) L.push('\n/* font <link>s: ' + tokens.fontLinks.join(' ') + ' */');
fs.writeFileSync(out, L.join('\n') + '\n');
B.writeJson(path.join(path.dirname(out), 'tokens.json'), { primary: P, customProps: cp, body: tokens.body, headings: tokens.headings, buttons: tokens.buttons, links: tokens.links, families, sizes, breakpoints: tokens.breakpoints, fontFaces: tokens.fontFaces, fontLinks: tokens.fontLinks, loadedFonts: tokens.loadedFonts });
console.log(B.fmtSummary({ status: 'ok', workspace: WS, wrote: [path.relative(WS, out), path.relative(WS, path.join(path.dirname(out), 'tokens.json'))], findings: [cpKeys.length + ' site custom props kept verbatim', families.length + ' font families, ' + sizes.length + ' sizes, ' + (tokens.colors || []).length + ' colors ranked', 'body ' + tokens.body.fontFamily.split(',')[0] + ' ' + tokens.body.fontSize + '/' + tokens.body.lineHeight + ' on ' + hex(tokens.body.background)], warnings: [], next: 'import tokens.css in the build; use per-section specs for exact values' }));
